version: 2
updates:
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - server

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - frontend

  - package-ecosystem: npm
    directory: /tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - tests

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
